### ISSUE TITLE
need

### ISSUE THREAD

**Issue by divians** [Sighmir/vrp_hotkeys#1]
You can sit down on a chair, and other animations on keys F1, F2 ... and others

**Comment by Armagryzor** [comment]
Hi Sighmir , 

With your script hotkeys , can you bind keys from vrp to cuff and uncuff , open/close vehicle?

Thank you so much

**Comment by Sighmir** [comment]
This is an interface for you to make any hotkey make any function on press and on release. You can bind keys to functions, if you just need to add the key and the function on the cfg/hotkeys.lua. 
I am not making every animation into a hotkey because that would take too many, other servers use those hotkeys and the resource is supposed to be used by everyone with no problems. 
You are free to add any function you want to any button on the hotkeys.lua.
